name: Sync Files

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '21 10 * * 5' # Run every Friday at 10:21 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.7.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_INSTALLATION_TOKEN: ${{ steps.generate_token.outputs.token }}
          GIT_EMAIL: 89714990+file-sync-app[bot]@users.noreply.github.com
          GIT_USERNAME: "file-sync-app[bot]"
          ORIGINAL_MESSAGE: true
          COMMIT_EACH_FILE: false
          SKIP_PR: true
